"""create initial tables

Revision ID: 4d3898328a3e
Revises: 
Create Date: 2026-05-06 07:40:37.306929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3898328a3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('online_store_url_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('is_weighted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    # First enable the extension, then create the index with the correct operator class
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index('ix_products_name_trgm', 'products', ['name'], 
                unique=False, postgresql_using='gin',
                postgresql_ops={"name": "gin_trgm_ops"})
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('delivery_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stores_chain_store', 'stores', ['chain_id', 'store_id'], unique=True)
    op.create_index('ix_stores_location', 'stores', ['latitude', 'longitude'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prices_is_current', 'prices', ['is_current'], unique=False)
    op.create_index('ix_prices_product_store', 'prices', ['product_id', 'store_id'], unique=False)
    op.create_index('ix_prices_scraped_at', 'prices', ['scraped_at'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discounted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_qty', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promotions_active', 'promotions', ['is_active'], unique=False)
    op.create_index('ix_promotions_product_store', 'promotions', ['product_id', 'store_id'], unique=False)
    op.create_index('ix_promotions_unique', 'promotions', ['promotion_id', 'store_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promotions_unique', table_name='promotions')
    op.drop_index('ix_promotions_product_store', table_name='promotions')
    op.drop_index('ix_promotions_active', table_name='promotions')
    op.drop_table('promotions')
    op.drop_index('ix_prices_scraped_at', table_name='prices')
    op.drop_index('ix_prices_product_store', table_name='prices')
    op.drop_index('ix_prices_is_current', table_name='prices')
    op.drop_table('prices')
    op.drop_index('ix_stores_location', table_name='stores')
    op.drop_index('ix_stores_chain_store', table_name='stores')
    op.drop_table('stores')
    op.drop_index('ix_products_name_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_table('products')
    op.drop_table('chains')
    # ### end Alembic commands ###
